// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5F9F0Gj-L4ttVz5PBeicthSFtl8K-nk',
    appId: '1:959197077184:web:fb23fee2f9f246a4ad1725',
    messagingSenderId: '959197077184',
    projectId: 'function-world-chat',
    authDomain: 'function-world-chat.firebaseapp.com',
    databaseURL: 'https://function-world-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'function-world-chat.appspot.com',
    measurementId: 'G-2TEM0K71FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAcR_pT0nCQjS1M89jBOMMGsPL-nrWNY',
    appId: '1:959197077184:android:620bec1848686f47ad1725',
    messagingSenderId: '959197077184',
    projectId: 'function-world-chat',
    databaseURL: 'https://function-world-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'function-world-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Fy6mu8qv1YGvWTP7IWiTsF8WIHe784U',
    appId: '1:959197077184:ios:4747848ef10ef5bead1725',
    messagingSenderId: '959197077184',
    projectId: 'function-world-chat',
    databaseURL: 'https://function-world-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'function-world-chat.appspot.com',
    iosBundleId: 'com.example.functionWorldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Fy6mu8qv1YGvWTP7IWiTsF8WIHe784U',
    appId: '1:959197077184:ios:4cd602881c4a4e52ad1725',
    messagingSenderId: '959197077184',
    projectId: 'function-world-chat',
    databaseURL: 'https://function-world-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'function-world-chat.appspot.com',
    iosBundleId: 'com.example.functionWorldApp.RunnerTests',
  );
}
